"""
ActionPlan schema - output from the Action Planner Agent.

Represents corrective action plans with tasks, standards references,
cost estimates, and lead times.
"""

from enum import Enum
from typing import Optional
from uuid import uuid4

from pydantic import BaseModel, Field


class ControlHierarchy(str, Enum):
    """
    Hierarchy of controls for hazard mitigation.

    Listed in order of effectiveness (most to least effective).
    Action Planner should prioritize higher-level controls.
    """
    ELIMINATION = "ELIMINATION"       # Remove the hazard entirely
    SUBSTITUTION = "SUBSTITUTION"     # Replace with less hazardous alternative
    ENGINEERING = "ENGINEERING"       # Isolate people from the hazard
    ADMINISTRATIVE = "ADMINISTRATIVE" # Change the way people work
    PPE = "PPE"                       # Personal protective equipment


class Task(BaseModel):
    """
    A single corrective action task within an action plan.

    Attributes:
        task_id: Unique identifier for this task
        title: Short title describing the task
        description: Detailed description of what needs to be done
        control_type: Hierarchy of controls category
        responsible_role: Role/position responsible for execution
        duration_minutes: Estimated duration in minutes
        material_requirements: List of materials needed
        acceptance_criteria: Criteria to verify task completion

    Example:
        >>> task = Task(
        ...     title="Install toe boards on scaffolding",
        ...     description="Install 150mm toe boards on all scaffolding platforms",
        ...     control_type=ControlHierarchy.ENGINEERING,
        ...     responsible_role="scaffolder",
        ...     duration_minutes=120,
        ...     material_requirements=["toe_boards", "fixings"],
        ...     acceptance_criteria="All platforms have toe boards, no gaps > 25mm"
        ... )
    """

    task_id: str = Field(
        default_factory=lambda: str(uuid4()),
        description="Unique identifier for this task"
    )
    title: str = Field(
        ...,
        description="Short title for the task"
    )
    description: str = Field(
        ...,
        description="Detailed description of the task"
    )
    control_type: ControlHierarchy = Field(
        ...,
        description="Hierarchy of controls category"
    )
    responsible_role: str = Field(
        ...,
        description="Role responsible for task execution"
    )
    duration_minutes: int = Field(
        ...,
        ge=0,
        description="Estimated duration in minutes"
    )
    material_requirements: list[str] = Field(
        default_factory=list,
        description="List of materials needed"
    )
    acceptance_criteria: str = Field(
        ...,
        description="Criteria for verifying task completion"
    )


class ActionPlan(BaseModel):
    """
    Corrective action plan generated by the Action Planner Agent.

    Contains tasks aligned with safety standards (OSHA, ISO 45001),
    following the hierarchy of controls principle.

    Attributes:
        plan_id: Unique identifier for this plan
        hazard_id: Reference to the scored hazard
        tasks: List of corrective action tasks
        standards_refs: References to applicable safety standards
        cost_estimate_usd: Total estimated cost in USD
        lead_time_days: Estimated days to complete all tasks
        notes: Additional notes or recommendations

    Example:
        >>> plan = ActionPlan(
        ...     hazard_id="haz-456",
        ...     tasks=[task1, task2],
        ...     standards_refs=["OSHA 1926.451(g)(4)", "ISO 45001:2018 8.1.2"],
        ...     cost_estimate_usd=450.00,
        ...     lead_time_days=2
        ... )
    """

    plan_id: str = Field(
        default_factory=lambda: str(uuid4()),
        description="Unique identifier for this plan"
    )
    hazard_id: str = Field(
        ...,
        description="Reference to the scored hazard"
    )
    tasks: list[Task] = Field(
        ...,
        min_length=1,
        description="List of corrective action tasks"
    )
    standards_refs: list[str] = Field(
        default_factory=list,
        description="References to applicable safety standards"
    )
    cost_estimate_usd: float = Field(
        ...,
        ge=0,
        description="Total estimated cost in USD"
    )
    lead_time_days: int = Field(
        ...,
        ge=0,
        description="Estimated days to complete all tasks"
    )
    notes: Optional[str] = Field(
        default=None,
        description="Additional notes or recommendations"
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "plan_id": "plan-789",
                "hazard_id": "haz-456",
                "tasks": [
                    {
                        "task_id": "task-001",
                        "title": "Install toe boards",
                        "description": "Install 150mm toe boards on all scaffolding platforms",
                        "control_type": "ENGINEERING",
                        "responsible_role": "scaffolder",
                        "duration_minutes": 120,
                        "material_requirements": ["toe_boards", "fixings"],
                        "acceptance_criteria": "All platforms have toe boards"
                    }
                ],
                "standards_refs": ["OSHA 1926.451(g)(4)", "ISO 45001:2018 8.1.2"],
                "cost_estimate_usd": 450.00,
                "lead_time_days": 2,
                "notes": "Priority should be given to highest levels"
            }
        }
    }
