"""
Observation schema - the canonical input to the safety observation pipeline.

This model corresponds to the observation request shape from the production platform:
{
  "observedAt": "2025-11-24T10:15:00Z",
  "site": "Building A - 3rd floor",
  "potential": "NEAR_MISS",
  "type": "AREA_FOR_IMPROVEMENT",
  "tradeCategoryId": "trade_cat_1",
  "tradePartnerId": "partner_1",
  "description": "Scaffolding board slipped but worker caught it before falling.",
  "photoId": "file_987"
}
"""

from datetime import datetime
from enum import Enum
from typing import Optional
from uuid import uuid4

from pydantic import BaseModel, Field


class ObservationPotential(str, Enum):
    """
    Potential severity classification for an observation.

    Represents the potential outcome if the observed condition
    had resulted in an incident.
    """
    NEAR_MISS = "NEAR_MISS"
    FIRST_AID = "FIRST_AID"
    MEDICAL_TREATMENT = "MEDICAL_TREATMENT"
    LOST_TIME = "LOST_TIME"
    FATALITY = "FATALITY"


class ObservationType(str, Enum):
    """
    Type classification for the observation.

    Categorizes the nature of the safety observation.
    """
    AREA_FOR_IMPROVEMENT = "AREA_FOR_IMPROVEMENT"
    UNSAFE_ACT = "UNSAFE_ACT"
    UNSAFE_CONDITION = "UNSAFE_CONDITION"
    POSITIVE_OBSERVATION = "POSITIVE_OBSERVATION"
    ENVIRONMENTAL = "ENVIRONMENTAL"


class Observation(BaseModel):
    """
    Safety observation submitted by a user.

    This is the SOURCE OF TRUTH for the pipeline input.
    All agents receive data derived from this observation.

    Attributes:
        id: Internal unique identifier (generated by backend)
        observed_at: Timestamp when the observation was made
        site: Location identifier (e.g., "Building A - 3rd floor")
        potential: Potential severity if incident had occurred
        type: Category of the observation
        trade_category_id: Optional trade category reference
        trade_partner_id: Optional trade partner reference
        description: Free-text description of what was observed
        photo_id: Optional reference to attached photo/media

    Example:
        >>> obs = Observation(
        ...     observed_at=datetime.now(),
        ...     site="Building A - 3rd floor",
        ...     potential=ObservationPotential.NEAR_MISS,
        ...     type=ObservationType.AREA_FOR_IMPROVEMENT,
        ...     description="Scaffolding board slipped but worker caught it"
        ... )
    """

    # Internal ID - generated by the system
    id: str = Field(default_factory=lambda: str(uuid4()))

    # Required fields from the request
    observed_at: datetime = Field(
        ...,
        alias="observedAt",
        description="Timestamp when the observation was made"
    )
    site: str = Field(
        ...,
        min_length=1,
        description="Location identifier where observation occurred"
    )
    potential: ObservationPotential = Field(
        ...,
        description="Potential severity classification"
    )
    type: ObservationType = Field(
        ...,
        description="Type/category of the observation"
    )
    description: str = Field(
        ...,
        min_length=1,
        description="Free-text description of the observation"
    )

    # Optional fields
    trade_category_id: Optional[str] = Field(
        default=None,
        alias="tradeCategoryId",
        description="Reference to trade category"
    )
    trade_partner_id: Optional[str] = Field(
        default=None,
        alias="tradePartnerId",
        description="Reference to trade partner"
    )
    photo_id: Optional[str] = Field(
        default=None,
        alias="photoId",
        description="Reference to attached photo/media"
    )

    model_config = {
        "populate_by_name": True,  # Allow both alias and field name
        "json_schema_extra": {
            "example": {
                "observedAt": "2025-11-24T10:15:00Z",
                "site": "Building A - 3rd floor",
                "potential": "NEAR_MISS",
                "type": "AREA_FOR_IMPROVEMENT",
                "tradeCategoryId": "trade_cat_1",
                "tradePartnerId": "partner_1",
                "description": "Scaffolding board slipped but worker caught it before falling.",
                "photoId": "file_987"
            }
        }
    }
